# /*******************************************************************************
#  * Copyright 2018 Dell Inc.
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
#  * in compliance with the License. You may obtain a copy of the License at
#  *
#  * http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software distributed under the License
#  * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  * or implied. See the License for the specific language governing permissions and limitations under
#  * the License.
#  *
#  * @author: Jim White, Dell
#  * EdgeX Foundry, Developer Docker Compose
#  * added: Nov 16, 2018
#  *
#  * @author: Bindu Rao, IOTech
#  * For device-grove service on Raspberry Pi (arm64)
#  * updated: Dec 07, 2018
#  *
#  * @author: Bindu Rao, IOTech
#  * To use latest version(0.7.1) of core services
#  * updated: Dec 11, 2018
#  *
#  * @author: Bindu Rao, IOTech
#  * To use latest version(1.0.0) of core services
#  * updated: Jun 19, 2019
#
#  * @author: Bindu Rao, IOTech
#  * updated edgex-volume and edgex-mongo image version to 1.0.0
#  * updated: July 04, 2019
#
#  * @author: Alex Courouble
#  * updated Commented out device-grove
#  * updated: August 28, 2019
#
#  *******************************************************************************/

version: '3'
volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:
  portainer_data:

services:
  volume:
    image: edgexfoundry/docker-edgex-volume-arm64:1.0.0
    container_name: edgex-files
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data

  consul:
    image: consul:1.3.1
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    container_name: edgex-core-consul
    hostname: edgex-core-consul
    networks:
      edgex-network:
        aliases:
          - edgex-core-consul
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume

  config-seed:
    image: edgexfoundry/docker-core-config-seed-go-arm64:1.0.0
    container_name: edgex-config-seed
    hostname: edgex-core-config-seed
    networks:
      edgex-network:
        aliases:
          - edgex-core-config-seed
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - consul

  mongo:
    image: edgexfoundry/docker-edgex-mongo-arm64:1.0.0
    ports:
      - "27017:27017"
    container_name: edgex-mongo
    hostname: edgex-mongo
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume

  logging:
    image: edgexfoundry/docker-support-logging-go-arm64:1.0.0
    ports:
      - "48061:48061"
    container_name: edgex-support-logging
    hostname: edgex-support-logging
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - config-seed
      - mongo
      - volume

  notifications:
    image: edgexfoundry/docker-support-notifications-go-arm64:1.0.0
    ports:
      - "48060:48060"
    container_name: edgex-support-notifications
    hostname: edgex-support-notifications
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - logging

  metadata:
    image: edgexfoundry/docker-core-metadata-go-arm64:1.0.0
    ports:
      - "48081:48081"
    container_name: edgex-core-metadata
    hostname: edgex-core-metadata
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - logging

  data:
    image: edgexfoundry/docker-core-data-go-arm64:1.0.0
    ports:
      - "48080:48080"
      - "5563:5563"
    container_name: edgex-core-data
    hostname: edgex-core-data
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - logging

  command:
    image: edgexfoundry/docker-core-command-go-arm64:1.0.0
    ports:
      - "48082:48082"
    container_name: edgex-core-command
    hostname: edgex-core-command
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - metadata

  export-client:
    image: edgexfoundry/docker-export-client-go-arm64:1.0.0
    ports:
      - "48071:48071"
    container_name: edgex-export-client
    hostname: edgex-export-client
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - data
    environment:
      - EXPORT_CLIENT_MONGO_URL=edgex-mongo
      - EXPORT_CLIENT_DISTRO_HOST=edgex-export-distro
      - EXPORT_CLIENT_CONSUL_HOST=edgex-config-seed

  export-distro:
    image: edgexfoundry/docker-export-distro-go-arm64:1.0.0
    ports:
      - "48070:48070"
      - "5566:5566"
    container_name: edgex-export-distro
    hostname: edgex-export-distro
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - export-client
    environment:
      - EXPORT_DISTRO_CLIENT_HOST=edgex-export-client
      - EXPORT_DISTRO_DATA_HOST=edgex-core-data
      - EXPORT_DISTRO_CONSUL_HOST=edgex-config-seed
      - EXPORT_DISTRO_MQTTS_CERT_FILE=none
      - EXPORT_DISTRO_MQTTS_KEY_FILE=none


  #################################################################
  # Device Services
  #################################################################

  # device-grove:
  #   image: edgexfoundry/docker-device-grove-c-arm64:1.0.1
  #   ports:
  #     - "49991:49991"
  #   devices:
  #     - /dev/i2c-1
  #   container_name: edgex-device-grove
  #   hostname: edgex-device-grove
  #   networks:
  #     - edgex-network
  #   volumes:
  #     - db-data:/data/db
  #     - log-data:/edgex/logs
  #     - consul-config:/consul/config
  #     - consul-data:/consul/data
  #   depends_on:
  #     - data
  #     - command

  #   device-bluetooth:
  #     image: nexus3.edgexfoundry.org:10004/docker-device-bluetooth:0.6.0
  #     ports:
  #       - "49988:49988"
  #       - "5000:5000"
  #     container_name: edgex-device-bluetooth
  #     hostname: edgex-device-bluetooth
  #     privileged: true
  #     network_mode: "host"
  #     cap_add:
  #       - NET_ADMIN
  # #    networks:
  # #      - edgex-network
  #    volumes:
  #      - db-data:/data/db
  #      - log-data:/edgex/logs
  #      - consul-config:/consul/config
  #      - consul-data:/consul/data
  #     depends_on:
  #       - data
  #       - command

  #   device-snmp:
  #     image: nexus3.edgexfoundry.org:10004/docker-device-snmp:0.6.0
  #     ports:
  #       - "49989:49989"
  #     container_name: edgex-device-snmp
  #     hostname: edgex-device-snmp
  #     networks:
  #       - edgex-network
  #    volumes:
  #      - db-data:/data/db
  #      - log-data:/edgex/logs
  #      - consul-config:/consul/config
  #      - consul-data:/consul/data
  #     depends_on:
  #       - data
  #       - command

  #   device-modbus:
  #     image: nexus3.edgexfoundry.org:10004/docker-device-modbus:0.6.0
  #     ports:
  #       - "49991:49991"
  #     container_name: edgex-device-modbus
  #     networks:
  #       - edgex-network
  #    volumes:
  #      - db-data:/data/db
  #      - log-data:/edgex/logs
  #      - consul-config:/consul/config
  #      - consul-data:/consul/data
  #     privileged: true
  #     depends_on:
  #       - data
  #       - command

  #   device-fischertechnik:
  #     image: nexus3.edgexfoundry.org:10004/docker-device-fischertechnik:0.6.0
  #     ports:
  #       - "49985:49985"
  #     container_name: edgex-device-fischertechnik
  #     networks:
  #       - edgex-network
  #    volumes:
  #      - db-data:/data/db
  #      - log-data:/edgex/logs
  #      - consul-config:/consul/config
  #      - consul-data:/consul/data
  #     privileged: true
  #     depends_on:
  #       - data
  #       - command

  #   device-bacnet:
  #     image: nexus3.edgexfoundry.org:10004/docker-device-bacnet:0.6.0
  #     ports:
  #       - "49986:49986"
  #       - "5002:5002"
  #     container_name: edgex-device-bacnet
  #     hostname: edgex-device-bacnet
  #     networks:
  #       - edgex-network
  #    volumes:
  #      - db-data:/data/db
  #      - log-data:/edgex/logs
  #      - consul-config:/consul/config
  #      - consul-data:/consul/data
  #    depends_on:
  #       - data
  #       - command

  #   device-mqtt:
  #     image: nexus3.edgexfoundry.org:10004/docker-device-mqtt:0.6.0
  #     ports:
  #       - "49982:49982"
  #       - "14377:14377"
  #     container_name: edgex-device-mqtt
  #     hostname: edgex-device-mqtt
  #     networks:
  #       - edgex-network
  #    volumes:
  #      - db-data:/data/db
  #      - log-data:/edgex/logs
  #      - consul-config:/consul/config
  #      - consul-data:/consul/data
  #     depends_on:
  #       - data
  #       - command

  #################################################################
  # UIs
  #################################################################
  # to be done

  #################################################################
  # Tooling
  #################################################################

  portainer:
    image:  portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    depends_on:
      - volume

networks:
  edgex-network:
    driver: "bridge"
...